env:
  CONTAINER_IMAGE_TAG: githubchangeloggenerator/github-changelog-generator:latest

name: Build and deploy latest image

on: [push, pull_request]

jobs:
  lint:
    name: Lint the codebase
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Super-Linter
        uses: github/super-linter@v3.15.5
        env:
          ERROR_ON_MISSING_EXEC_BIT: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: .
          VALIDATE_ALL_CODEBASE: true
  build:
    name: Build and test the container image
    needs: lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Build the container image for x86_64 only
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: false
          tags: ${{ env.CONTAINER_IMAGE_TAG }}
      - name: Test the container image
        shell: bash
        run: docker run ${{ env.CONTAINER_IMAGE_TAG }}
  deploy:
    env:
      PUSH_IMAGES: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    environment: Docker Hub
    if: ${{ env.PUSH_IMAGES }}
    name: Deploy the container image
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build the contaiiner image for all the platforms and eventually push to Docker Hub (latest)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          push: ${{ env.PUSH_IMAGES }}
          tags: ${{ env.CONTAINER_IMAGE_TAG }}
