name: Deploy tagged image

on:
  release:
    types: [created]

jobs:
  push:
    if: github.event_name == 'release' && github.event.action == 'created'
    name: Deploy tagged image
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to Docker Hub (tagged)
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ferrarimarco/github-changelog-generator:${{ github.event.release.tag_name }}
